language: erlang
sudo: false
otp_release:
  - 20.0 

script:
  - ./rebar3 compile
  - ./rebar3 eunit
  - ./rebar3 dialyzer
  - ./rebar compile
  - ./rebar skip_deps=true eunit

cache:
  directories:
    - $HOME/.cache
